[package]
name = "takeoff-mailer"
version = "0.1.0"
edition = "2024"

[dependencies]
prost = "0.12"
lapin = "2.3"
tokio = { version = "1", features = ["full"] }
futures-util = "0.3.31"
prost-types = "0.14.3"
dotenvy = "0.15.7"
lettre = "0.11.19"

[build-dependencies]
prost-build = "0.12"
